[package]
name = "table-test"
version = "0.0.1"

[addresses]
StarcoinFramework = "0x1"
TableTest = "0xed9ea1f3533c14e1b52d9ff6475776ba"

[dependencies]
StarcoinFramework = {git = "https://github.com/starcoinorg/starcoin-framework.git", rev="345a3900a0064dc57a9560235bc72c12f03448b1"}
